import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = '/Users/mo/Public/Images';
const TARGET_DIR = path.join(__dirname, '../public/gallery');
const DATA_FILE = path.join(__dirname, '../src/data/gallery.js');

const VALID_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp'];

function syncGallery() {
  console.log('--- Starting Gallery Sync ---');

  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`);
    return;
  }

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
  }

  const sourceFiles = fs.readdirSync(SOURCE_DIR)
    .filter(file => VALID_EXTENSIONS.includes(path.extname(file).toLowerCase()));

  const targetFiles = fs.readdirSync(TARGET_DIR);

  // 1. Remove files in target that are no longer in source
  targetFiles.forEach(file => {
    if (!sourceFiles.includes(file)) {
      console.log(`Removing: ${file}`);
      fs.unlinkSync(path.join(TARGET_DIR, file));
    }
  });

  // 2. Copy files from source to target if they don't exist or are different
  sourceFiles.forEach(file => {
    const srcPath = path.join(SOURCE_DIR, file);
    const destPath = path.join(TARGET_DIR, file);

    if (!fs.existsSync(destPath)) {
      console.log(`Adding: ${file}`);
      fs.copyFileSync(srcPath, destPath);
    }
  });

  // 3. Regenerate gallery.js
  const galleryData = sourceFiles.map(file => {
    // Randomized col/row spans for the brutalist look
    // 70% chance of 1x1, 20% 2x1/1x2, 10% 2x2
    const rand = Math.random();
    let col = 1, row = 1;
    if (rand > 0.9) { col = 2; row = 2; }
    else if (rand > 0.8) { col = 2; row = 1; }
    else if (rand > 0.7) { col = 1; row = 2; }

    return { file, col, row };
  });

  const content = `// Auto-generated by scripts/sync-gallery.js
// Total images: ${galleryData.length}

const images = ${JSON.stringify(galleryData, null, 2)};

export default images;
`;

  fs.writeFileSync(DATA_FILE, content);
  console.log(`--- Sync Complete! Total Images: ${galleryData.length} ---`);
}

syncGallery();
